theme: jekyll-theme-cayman
# Site settings
title: David Dai IT Blog                     #你博客的标题
SEOTitle: 你的博客 | You Blog        #显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-rwd.jpg     #显示在首页的背景图片
email: dai08170@gmail.com    
description: "David Dai Blog"              #网站介绍
keyword: "BY, BY Blog, ERP,Ecommerce,AI,Bigdata" #关键词
url: "https://davidblog.github.io"          # 这个就是填写你的博客地址
baseurl: ""      # 这个我们不用填写



# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "放眼看世界，IT风云录"
# 你的个人头像 可以放在 sidebar-avatar:/img/avatar-m.JPG 这里你可以改成我在img文件夹中的两张备用照片 img/avatar-m 或 avatar-g



# SNS settings
RSS: false
weibo_username:     username
zhihu_username:     username
github_username:    username
facebook_username:  username
jianshu_username:   jianshu_id


# Disqus settings（https://disqus.com/）
disqus_username: disqus_hulm1gyNJ1

friends: [
    {
        title: "简书·BY",
        href: "http://www.jianshu.com/u/e71990ada2fd"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
